name: Environment cleanup
on:
  push:
    branches: [ master ]
  pull_request:
    branches: 
    - '!master'
    - '!development'
    - 'OT-'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: commit delete env
      run: |
        git commit --allow-empty -m "Deleting branch environment [delete env!]" 
        git push
