name: Environment cleanup
on:
  pull_request:
    types: [ closed ]
    branches: 
    - 'OT-*'
    - '!master'
    - '!development'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4.1.6
      with:
        commit_message: testtttt fjdnfjdnjfndjnfd
